### ISSUE TITLE
model file are not downloading.

### ISSUE THREAD

**Issue by upendrasingh18** [sk217/dog-breed-classifier#1]
the three model files model_8.h5 ,model_16.h5 ,yolo.h5 are not downloading because the link is not working. can you please share the link to download these.

**Comment by sk217** [comment]
@upendrasingh18 

Thanks for the report. Just erased yesterday:/
Now that it has been restored, you should be able to get it.

By the way, this project was created when I didn't know anything about Python or image processing.
So I think there are many bugs and I don't know if the restored models is accurate.
There are no plans for maintenance in the future.
Thank you:)

**Comment by upendrasingh18** [comment]
Thanks a lot @sk217  for reloading the models. It's no problem I will check bugs and try to solve them.
